[keybindings]
[keybindings.EventLogDetail]
"<?>"      = "HelpShow"
"<Ctrl-c>" = "Quit"
"<Ctrl-d>" = "Quit"
"<Ctrl-z>" = "Suspend"
"<Down>"   = "EventLogNext"
"<End>"    = "EventLogLast"
"<Esc>"    = "EventLogListShow"
"<Home>"   = "EventLogTop"
"<Up>"     = "EventLogPrevious"
"<c>"      = "EventLogFilterCreate"
"<q>"      = "Quit"

[keybindings.Filter]
"<a>"         = "FilterAdd"
"<Ctrl-c>"    = "Quit"
"<Ctrl-d>"    = "Quit"
"<Ctrl-z>"    = "Suspend"
"<Backspace>" = "FilterDelete"
"<Down>"      = "FilterNext"
"<End>"       = "FilterLast"
"<Enter>"     = "FilterEdit"
"<Esc>"       = "FilterHide"
"<Home>"      = "FilterTop"
"<q>"         = "Quit"
"<Up>"        = "FilterPrevious"
"<?>"         = "HelpShow"

[keybindings.EventLogFilterCreate]
"<?>"     = "HelpShow"
"<Tab>"   = "FilterCreateNext"
"<Esc>"   = "FilterCreateCancel"
"<Enter>" = "FilterCreateToggle"

[keybindings.FilterEdit]
"<Enter>" = "FilterSubmit"
"<Esc>"   = "FilterCancel"
"<?>"     = "HelpShow"

[keybindings.Format]
"<Ctrl-c>" = "Quit"
"<Ctrl-d>" = "Quit"
"<Ctrl-z>" = "Suspend"
"<Down>"   = "FormatRowNext"
"<End>"    = "FormatRowLast"
"<Enter>"  = "FormatRowEdit"
"<Esc>"    = "FormatHide"
"<Home>"   = "FormatRowTop"
"<q>"      = "Quit"
"<Up>"     = "FormatRowPrevious"
"<?>"      = "HelpShow"

[keybindings.Help]
"<?>"   = "HelpHide"
"<Esc>" = "HelpHide"

[keybindings.Home]
"<Alt-Left>"    = "EventLogScrollReset"
"<Ctrl-c>"      = "Quit"
"<Ctrl-d>"      = "Quit"
"<Ctrl-Left>"   = "EventLogScrollReset"
"<Ctrl-z>"      = "Suspend"
"<Shift-Left>"  = "EventLogScrollLeftBig"
"<Shift-Right>" = "EventLogScrollRightBig"
"<Down>"        = "EventLogNext"
"<End>"         = "EventLogLast"
"<Enter>"       = "EventLogDetailShow"
"<Esc>"         = "EventLogSelectClear"
"<e>"           = "FilterShow"
"<f>"           = "FormatShow"
"<Home>"        = "EventLogTop"
"<Left>"        = "EventLogScrollLeft"
"<q>"           = "Quit"
"<Right>"       = "EventLogScrollRight"
"<Up>"          = "EventLogPrevious"
"<w>"           = "EventLogWrapToggle"
"<?>"           = "HelpShow"
